apiVersion: v1
kind: Secret
metadata:
  name: {{ include "practical.fullname" . }}
  labels:
    {{- include "practical.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb_url: {{ include "practical.mongodb_url" . | b64enc | quote }}
