apiVersion: v1
kind: Service
metadata:
  name: {{ include "practical.fullname" . }}
  labels:
    {{- include "practical.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "practical.selectorLabels" . | nindent 4 }}
